server:
  port: 8080
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  mapper-locations:
    - classpath*:indi/**/dao/*.xml
captcha:
  font:
    size: 30
    color: black
    names: 宋体,楷体,微软雅黑
  image:
    width: 110
    height: 38
  char-length: 5