server:
  port: 8080
  servlet:
    session:
      timeout: 86400
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static
  thymeleaf:
    #设置thymeleaf页面缓存失效
    cache: false
    #thymeleaf模版前缀，默认值,可选项
    prefix: classpath:/templates/
    #thymeleaf模版后缀，默认值,可选项
    suffix: .html
mybatis:
  mapper-locations:
    - classpath*:indi/**/dao/*.xml
captcha:
  font:
    size: 30
    color: black
    names: 宋体,楷体,微软雅黑
  image:
    width: 110
    height: 38
  char-length: 5
logging:
  level:
    indi.zhzl.myblognext.dao: debug
upload-path: /static/upload