server:
  port: 8080
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static
  thymeleaf:
    #??thymeleaf??????
    cache: false
    #thymeleaf????????,???
    prefix: classpath:/templates/
    #thymeleaf????????,???
    suffix: .html
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml